FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies (include devDependencies for nodemon in localdev)
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

ENV NODE_ENV=development
EXPOSE 3000

# Use nodemon for dev live-reload. Use npx so we don't need global install.
CMD ["npx", "nodemon", "./src/index.mjs"]
